**Installing numpy Python library**

Open terminal 

give the command <code>pip3 install numpy<code>

# What is numpy

It is an important python Library used for working with arrays.

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


In [1]:
import numpy as np


In [2]:
l= [2,3,4,5]
arr= np.array(l)
print(arr)

[2 3 4 5]


### Advantage of numpy over Lists

1. Numpy occcupies much less space than a list
2. Numpy are faster than lists
3. Numpy uses fixed datatypes
4. NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.
5. Numpy supports vectorized operations

In [3]:
a = [1,2,3,4,5]
b= [6,5,6,8,9]
c = []
for i in range(len(a)):
    c.append(a[i]*b[i])
print(c)

[6, 10, 18, 32, 45]


Here if we had many elements in both a and b then it would be difficult but it will be easy in Numpy because Numpy supports vectorized operations like it can add 2 array or multiply or do any operation in one step


In [4]:
a = np.array(a)
b = np.array(b)
c =  a*b
print (c)

[ 6 10 18 32 45]


In [5]:
# Get Dimension:- NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.
a.ndim

1

In [6]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim) 

0
1
2
3


In [7]:
# Access Array Elements
print(b[2])
print (c[1,1])
print (d[0,1,2])

# we can give negetive Index
# here if we want to access last element we can give index as -1 or to access second last element -2
print(c[0,-1])
print(d[-1,-2,0])


3
5
6
3
1


In [8]:
# arrays are group of homogenous elements which means each array can have only one type of elements
a= np.array([1,2,3,4,5])
print(a.dtype)
b=np.array([1.4,5.7,6.1])
c=np.array(["goals","dreams","war","peace"])
print(b.dtype)
print(c.dtype)

int64
float64
<U6


In [9]:
# In above example datatype is created by default but we can also give datatype while creating an array

a= np.array([1,2,3,4],dtype='int32') 
print(a.dtype) 
# and .dtype is used to give the datatype of the array

int32


we have many datatypes and we use characters to repreasent them


    i - integer
    b - boolean
    u - unsigned integer
    f - float
    c - complex float
    m - timedelta
    M - datetime
    O - object
    S - string
    U - unicode string
    V - fixed chunk of memory for other type ( void )
    
### Syntax
arr_name = np.array([ele1,ele2,ele3...],dtype="datatype")

In [10]:
# we can convert some datatypes in array
arr = np.array([1.1,2.5,6.0])
newarr = arr.astype(int)
print(newarr)
# but sometime we can not convert datatypes

[1 2 6]


In [11]:
# Slicing arrays
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5]) #it includes start (index:1) and till end-1(exclusive of end)(end=index:5) 
print(arr[:3]) # here it take start as index 0 and print till 3-1 element
print(arr[2:]) # here it starts from index 2 and print till the end of array

[2 3 4 5]
[1 2 3]
[3 4 5 6 7]


In [12]:
# Negative Slicing
print(arr[-3:-1]) 
print(arr[:-2])
print(arr[-1:])

[5 6]
[1 2 3 4 5]
[7]


In [13]:
# Get Shape 
#The shape of an array is the number of elements in each dimension.

arr= np.array([[1,2,3],[4,5,6],[0,5,7]])
print(arr.shape)
a= np.array([[[1,2,3],[4,5,6]],[[0,9,8],[7,6,5]]])
print(a.shape)


(3, 3)
(2, 2, 3)


In [14]:
# we can create with different dimensions
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print(arr.shape)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


In [15]:
# Reshaping arrays

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(6,2) # convert to 2d
print(newarr)
print("---------------------------------")
print(arr.reshape(2,3,2)) # convert to 3d


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
---------------------------------
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [16]:
# Get Size
a= np.array([5,3,2,0]) # size of int64 is 8 bytes
print(a.itemsize)
a= np.array([5,3,2,0],dtype="int32") #size of int32 is 4 bytes
print(a.itemsize)

8
4


In [17]:
# Get Size
print(a.size) # this gives the total elements present in the array
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b.size)

4
8


In [18]:
# Get total size
a.nbytes # each element of array a takes 4 bytes total there are 4 elements so total size= a.itemsize*a.size

16

In [19]:
# Splitting NumPy Arrays
# it splits the array and make different given number of elements
ar= np.array([1,2,3,4,5,6])
print(np.array_split(ar, 3))

[array([1, 2]), array([3, 4]), array([5, 6])]


### Initializing Different Types of Arrays

In [20]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [22]:
# Any other number
np.full((2,2), 7)

array([[7, 7],
       [7, 7]])

In [23]:
# arrange - here we give min element and max element and diffence between 2 adjecent elements
x=np.arange(3,10,2)
print(x)
# to make 2d or 3d array
print("-----------------------")
x=np.arange(6).reshape(3,2)
print(x)

[3 5 7 9]
-----------------------
[[0 1]
 [2 3]
 [4 5]]


In [24]:
# linspace - here it takes parametter (min ele,max ele,no of values)
x= np.linspace(3.5,10,4)
print(x)

[ 3.5         5.66666667  7.83333333 10.        ]


In [25]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.07244575, 0.16027282],
       [0.08453021, 0.77837365],
       [0.55016222, 0.57754469],
       [0.03844584, 0.95718232]])

In [26]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 0,  6,  3],
       [ 3, -2,  5],
       [ 4,  2,  2]])

In [27]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
arr= np.array([1,2,3,4])
x=arr
arr[0]=2
print(x)
print(arr)

[2 2 3 4]
[2 2 3 4]


In above example we copy(as it is done in other programming language) but if we change arr then x also change so we need to copy arr to x

In [29]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x) 

[42  2  3  4  5]
[1 2 3 4 5]


## Searching, Sorting

In [31]:
# Searching 
arr = np.array([1, 2, 3, 4, 5, 4, 4,6,7,8])

x = np.where(arr == 6)
y = np.where(arr%2 == 0)
print(y)
print(x) 

(array([1, 3, 5, 6, 7, 9]),)
(array([7]),)


In [32]:
# Sorting in 1d
arr = np.array([3, 2, 0, 1])

print(np.sort(arr)) 

[0 1 2 3]


In [33]:
# sorting in 2d
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr)) 


[[2 3 4]
 [0 1 5]]


## Mathematics

In [34]:
a = np.array([1,2,3,4])
print(a)
b=a + 2
print(b)

[1 2 3 4]
[3 4 5 6]


In [35]:
a -1

array([0, 1, 2, 3])

In [36]:
c=a * 2
d=a/2
print(c)
print(d)

[2 4 6 8]
[0.5 1.  1.5 2. ]


In [37]:
a**2

array([ 1,  4,  9, 16])

### Link for Mathematical functions

https://docs.scipy.org/doc/numpy/reference/routines.math.html